INSERT INTO fish (name, description) VALUES ("Akula", "This very nice fish");
INSERT INTO fish (name, description) VALUES ("Akula1", "This very nice fish");
INSERT INTO weather_state (type_data_weather, min, max , mark, fish_id) VALUES ("tempDataType", 7, 27, "ACTIVE", 1);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("pressDataType", 5, 21, "ACTIVE", 3);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("pressDataType", 5, 21, "UP", 3);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("pressDataType", 5, 21, "MIDDLE", 3);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("tempDataType", 5, 21, "DIP", 3);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("tempDataType", 5, 21, "NOACTIVE", 3);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("tempDataType", 1, 23, "HUNGRY", 2);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("tempDataType", 2, 25, "UP", 2);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("pressDataType", 5, 21, "NOACTIVE", 5);
INSERT INTO weather_state (type_data_weather, min, max, mark, fish_id) VALUES ("pressDataType", 5, 21, "ACTIVE", 6);