DROP TABLE IF EXISTS
fishes_nibble,
baits_to_fishes,
baits_to_seasons,
baits_to_baits_settings,
pond,
year_periods,
parameters_names,
fishes,
baits,
baits_settings,
daily_forecast_weathers,
messages,
seasons,
users;