package com.jean.analyzers.weather;

/**
 * Created by jean on 07.12.15.
 */
public interface ConstantsAnalyzer {

    double CRITICAL_HIGH_TEMPERATURE = 28.5;
    float CRITICAL_PRESSURE_CHANGES = 4.57f;
    float CRITICAL_TEMPERATURE_CHANGES = 4.5f;
    double CRITICAL_DIFFERENCE_TEMP = 8.3;
    
    double PERCENT_PRESSURE_CHANGES = 44.22;
    double PERCENT_TEMPERATURE_CHANGES = 32.25;
    
    float MAX_GENERAL_TEMPERATURE_CHANGES = 11.5f;
   
    double CRITICAL_WIND_SPEED = 7.1;
    double MIN_WIND_SPEED = 1.5;
    
  
    
    enum PARAMETER_NAMES {ENVIROMENT_TEMPERATURE, WATER_TEMPERATURE, PRESSURE, MOON_PHASE, TIME_DAY, TIME_YEAR}
    
//    enum BRIGHT_LEVEL {BRIGHT, WHITE, NATURAL, DARK}
    
    enum ALGA_LEVEL {CLEAR, OVERGROWN, TRASH}
    
    enum DEEP_LEVEL {SHALLOW, MIDDLE, DEEPLY, OVERDEEPLY}
    
    enum BAIT_TYPE {LIVEBAIT, VEGETALE, BOIL, SIMULATED}
    
    enum KEY_MESSAGE {STYRO_POP_UP, BOIL_POP_UP, TOP_POP_UP}
    
    enum LIVING_AREA {TOP, MIDDLE, BOTTOM, EVERPRESENT}
}
