package com.jean.analyzers.weather;

/**
 * Created by jean on 07.12.15.
 */
public interface ConstantsAnalyzer {

	double MIN_TEMP_CHANGES_PER_DAY = 1.6;
	double MAX_TEMP_CHANGES_PER_DAY = 4.5;
	double CRITICAL_TEMP_CHANGES_ALL_PERIOD = 11.5;
	double CRITICAL_HIGH_TEMP = 28.5;

	double MIN_PRESSURE_CHABGES_PER_DAY = 2.5;
	double MAX_PRESSURE_CHANGES_PER_DAY = 6.5;
	double CRITICAL_PRESSURE_CHANGES_ALL_PERIOD = 12;

	double PERCENT_PRESSURE_CHANGES = 18.18;
	double PERCENT_TEMPERATURE_CHANGES = 22.22;

	double CRITICAL_WIND_SPEED = 7.1;
	double MIN_WIND_SPEED = 1.5;

	enum PARAMETER_NAMES {
		ENVIROMENT_TEMPERATURE, WATER_TEMPERATURE, PRESSURE, MOON_PHASE, TIME_DAY, TIME_YEAR
	}

	// enum BRIGHT_LEVEL {BRIGHT, WHITE, NATURAL, DARK}

	enum ALGA_LEVEL {
		CLEAR, OVERGROWN, TRASH
	}

	enum DEEP_LEVEL {
		SHALLOW, MIDDLE, DEEPLY, OVERDEEPLY
	}

	enum BAIT_TYPE {
		LIVEBAIT, VEGETALE, BOIL, SIMULATED
	}

	enum KEY_MESSAGE {
		STYRO_POP_UP, BOIL_POP_UP, TOP_POP_UP
	}

	enum LIVING_AREA {
		TOP, MIDDLE, BOTTOM, EVERPRESENT
	}
}
